# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
title: Curso de Python Científico
email: fnbellomo@gmail.com
author: fnbellomo
description: > # this means to ignore newlines until "baseurl:"
  Curso-Taller de Programación Científica en Python para Ciencias de la Atmósfer  a y los Océanos ha realizarse desde el Lunes 1 al viernes 4 e agosto del 2016   en la UBA. Esta curso cuenta con el aval DCAO/FCEN-UBA.

keywords: Python científico, Curso, Atmósfera, Océanos, CIMA, DCAO/FCEN-UBA

# Server
#baseurl: ""
baseurl: "/wpc" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://pewen.github.io"

# Time zone
timezone: America/Argentina/Cordoba

# Build settings
markdown: kramdown
permalink: pretty
exclude: [.git, .gitignore]

debug: false
